language: node_js
node_js:
  - 'node'
notifications:
  email:
    on_failure: change
    on_success: never
install:
  - yarn install
script:
  - yarn test --coverage --coverageReporters=text-lcov | coveralls
  - commitlint-travis
before_deploy:
  - yarn build
# Define the release stage that runs semantic-release
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
