language: node_js
node_js:
  - "node"
notifications:
  email:
    on_failure: change
    on_success: never
install:
  - yarn install
script:
  - yarn test --coverage
before_deploy:
  - yarn build
  - cp production/** build
deploy:
  local_dir: 'build/'
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  target-branch: build
  on:
    branch: master
